TFile * tf1;
TFile * tf2;
TFile * tf3;
TFile * tf4;
TFile * tf5;
TFile * tf6;

void checkFlat(){
  TCanvas * c = new TCanvas("flatCheck","flatCheck",1150,600);
  c->Divide(2,1);
  tf1 = new TFile("../data/rpflat_combined.root");
  tf2 = new TFile("../data/rpflat_1_200.root");
  tf3 = new TFile("../data/rpflat_1101_1300.root");
  TH1D * Neg1 = (TH1D *) tf1->Get("v2analyzer/EventPlanes/EvtPTracksNegEtaGap/psi");
  TH1D * Pos1 = (TH1D *) tf1->Get("v2analyzer/EventPlanes/EvtPTracksPosEtaGap/psi");
  TH1D * Neg2 = (TH1D *) tf2->Get("v2analyzer/EventPlanes/EvtPTracksNegEtaGap/psi");
  TH1D * Pos2 = (TH1D *) tf2->Get("v2analyzer/EventPlanes/EvtPTracksPosEtaGap/psi");
  TH1D * Neg3 = (TH1D *) tf3->Get("v2analyzer/EventPlanes/EvtPTracksNegEtaGap/psi");
  TH1D * Pos3 = (TH1D *) tf3->Get("v2analyzer/EventPlanes/EvtPTracksPosEtaGap/psi");
  Neg1->SetLineWidth(2.5);
  Pos1->SetLineWidth(2.5);
  Neg2->SetLineColor(kRed);
  Pos2->SetLineColor(kRed);
  Neg3->SetLineColor(kBlue);
  Pos3->SetLineColor(kBlue);
  c->cd(1);
  Neg1->Scale(78./Neg1->Integral(1,200));
  Neg2->Scale(78./Neg2->Integral(1,200));
  Neg3->Scale(78./Neg3->Integral(1,200));
  Neg1->SetMaximum(1.2);
  Neg1->SetXTitle("#eta");
  Neg1->Draw();
  Neg2->Draw("same");
  Neg3->Draw("same");
  TLegend *leg = new TLegend(0.44,0.4,0.7,0.65,"Event Selection");
  leg->AddEntry(Neg1,"All Events","l");
  leg->AddEntry(Neg2,"1st 15\%","l");
  leg->AddEntry(Neg3,"Last 15\%","l");
  leg->Draw();
  TLatex * lat1 = new TLatex(-3.7,1.05,"EvtPTracksNegEtaGap");
  lat1->Draw();
  c->cd(2);
  Pos1->Scale(78./Pos1->Integral(1,200));
  Pos2->Scale(78./Pos2->Integral(1,200));
  Pos3->Scale(78./Pos3->Integral(1,200));
  Pos1->SetMaximum(1.2);
  Pos1->SetXTitle("#eta");
  Pos1->Draw();
  Pos2->Draw("same");
  Pos3->Draw("same");
  TLatex * lat2 = new TLatex(-3.7,1.05,"EvtPTracksPosEtaGap");
  lat2->Draw();
}
