#include <stdlib.h>
#include "TROOT.h"
#include "TCanvas.h"
#include "TPad.h"
#include "TH1D.h"
#include "TString.h"
#include "TCanvasImp.h"
#include "TGraphErrors.h"
#include <stdio.h>
#include <iostream>
#include "../../../RecoHI/HiEvtPlaneAlgos/interface/HiEvtPlaneList.h"
TH1D * _hrefA;
TH1D * _hrefB;
TGraphErrors * _g1;
TGraphErrors * _g2;
TGraphErrors * _g3;
TGraphErrors * _g4;
TGraphErrors * _g5;
TGraphErrors * _g6;
TFile * Rescor1;
TFile * Rescor2;
const static Double_t  _xminleg = 0.48;
const static Double_t  _yminleg = 0.70;
const static Double_t  _xmaxleg = 0.95;
const static Double_t  _ymaxleg = 0.87;
TCanvas * template(TString cantitle, TString ylabel, TString label1, TString label2, TString label3, Int_t nEP1, Int_t nEP2, Int_t nEP3, Int_t nEP4,  Int_t nCompare);
TGraphErrors * InputType1(TString fileName, Int_t & Num);
TGraphErrors * InputType1(int  minCent, int maxCent, double eta, TString tag, TString EP1, TString EP2,Int_t & Num) {
  TString name = Form("results/v2pt_EP_%d-%d_%02d-_%s_%s_%s.txt",minCent,maxCent,(int)(10*eta),tag.Data(),EP1.Data(),EP2.Data());
  if(EP2.Length()==0) name = Form("results/v2pt_EP_%d-%d_%02d_%s_%s.txt",minCent,maxCent,(int)(10*eta),tag.Data(),EP1.Data());
  return InputType1(name,Num);
}


void Compare() {
  Bool_t CompareEff100 = kFALSE;
  Bool_t CompareEff95 = kFALSE;
  Bool_t CompareEta00_08 = kFALSE;
  Bool_t CompareEta08_16 = kFALSE;
  Bool_t CompareEta16_20 = kFALSE;
  Bool_t CompareEta16_20vtx25 = kFALSE;
  Bool_t CompareEta20_24 = kFALSE;
  Bool_t CompareEta20_24vtx25 = kFALSE;
  Bool_t CompareEta22_24dz5Flat = kTRUE;
  Bool_t CompareEta22_24dz10Flat = kTRUE;
  Bool_t CompareLowPtCut = kFALSE;
  Bool_t Compare500PtCut = kFALSE;
  Bool_t Compare30PtCut = kFALSE;
  Bool_t Compare26PtCut = kFALSE;
  Bool_t Compare25PtCut26PtCut = kFALSE;
  Bool_t Compare22PtCut = kFALSE;
  Bool_t Compare18PtCut = kFALSE;
  Bool_t Compare00GapCenter = kFALSE;
  Bool_t Compare20GapCenter = kFALSE;
  Bool_t Compare20GapCenter25Gap = kFALSE;
  Bool_t Compare50GapCenter25Gap = kFALSE;
  Bool_t Compare40GapCenter = kFALSE;
  Bool_t Compare50GapCenter = kFALSE;
  Bool_t Compare60GapCenter = kFALSE;
  Bool_t Compare80GapCenter = kFALSE;
  Bool_t Compare100GapCenter = kFALSE;
  Bool_t Compare120GapCenter = kFALSE;
  Bool_t CompareNewFlatCentCuts = kFALSE;
  Bool_t CompareFlatOrder4 = kFALSE;
  Bool_t CompareNoFlattening = kFALSE;
  Bool_t CompareAMPTOrganwithGen = kFALSE;
  Bool_t CompareHydjetBasswithGen = kFALSE;

  Bool_t Compare25Gap = kFALSE;
  Bool_t Compare375Gap = kFALSE;
  Bool_t Compare500Gap = kFALSE;
  Bool_t Compare625Gap = kFALSE;
  Bool_t Compare750Gap = kFALSE;
  Bool_t Compare875Gap = kFALSE;
  Bool_t CompareETHF = kFALSE;

  _hrefA = new TH1D ("hRef1","v_{2}",500,0,12);
  _hrefA->SetMaximum(0.4);
  _hrefA->SetXTitle("p_{T} (GeV/c)");
  _hrefB = new TH1D ("hRef2","v_{2}",500,0,12);
  _hrefB->SetXTitle("p_{T} (GeV/c)");
  _hrefB->SetMaximum(0.4);
  Int_t nPts1;
  Int_t nPts2;
  Int_t nPts3;
  Int_t nPts4;
  Int_t nPts5;
  Int_t nPts6;
  TString ylabel = "v_{2}";
  Int_t minCent1 = 0;
  Int_t maxCent1 = 5;
  Int_t minCent2 = 5;
  Int_t maxCent2 = 10;
  Int_t minCent3 = 15;
  Int_t maxCent3 = 20;

  TString label1 = Form("%d-%d",minCent1,maxCent1);
  TString label2 = Form("%d-%d",minCent2,maxCent2);
  TString label3 = Form("%d-%d",minCent3,maxCent3);
  label1+="\%";
  label2+="\%";
  label3+="\%";
  cout<<label1.Data()<<endl;
  cout<<label2.Data()<<endl;
  cout<<label3.Data()<<endl;
  if(CompareEff95) {
    TString tag1 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_eff95";
    TString tag2 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g1->SetTitle("Eff95");
    _g2 =  InputType1(minCent1, maxCent1, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g2->SetTitle("Eff97");
    _g3 =  InputType1(minCent2, maxCent2, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g3->SetTitle("Eff95");
    _g4 =  InputType1(minCent2, maxCent2, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g4->SetTitle("Eff97");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g5->SetTitle("Eff95");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g6->SetTitle("Eff97");
    
    TString cantitle = "CompareEff95";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareEff100) {
    TString tag1 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_eff100";
    TString tag2 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g1->SetTitle("Eff100");
    _g2 =  InputType1(minCent1, maxCent1, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g2->SetTitle("Eff97");
    _g3 =  InputType1(minCent2, maxCent2, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g3->SetTitle("Eff100");
    _g4 =  InputType1(minCent2, maxCent2, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g4->SetTitle("Eff97");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g5->SetTitle("Eff100");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g6->SetTitle("Eff97");
    
    TString cantitle = "CompareEff100";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareEta00_08) {
    TString tag1 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5";
    TString tag2 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5";
    int nEP1 = etHF;
    int nEP2 = etHF;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    tag1="NegEta-_"+tag1;
    tag2="PosEta-_"+tag2;
    _g1 =  InputType1(minCent1, maxCent1, 0.8, tag1, EPNames[nEP1],"",nPts1); 
    _g1->SetTitle("-0.8 #leq #eta < 0.0");
    _g2 =  InputType1(minCent1, maxCent1, 0.8, tag2, EPNames[nEP2],"",nPts2); 
    _g2->SetTitle("0.0 #leq #eta < 0.8");
    _g3 =  InputType1(minCent2, maxCent2, 0.8, tag1, EPNames[nEP1],"",nPts3); 
    _g3->SetTitle("-0.8 #leq #eta < 0.0");
    _g4 =  InputType1(minCent2, maxCent2, 0.8, tag2, EPNames[nEP2],"",nPts4); 
    _g4->SetTitle("0.0 #leq #eta < 0.8");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],"",nPts5); 
    _g5->SetTitle("-0.8 #leq #eta < 0.0");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP2],"",nPts6); 
    _g6->SetTitle("0.0 #leq #eta < 0.8");
    
    TString cantitle = "CompareEta00_08";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
     TFile * tfeff = new TFile("trkCorrFlow_ampt30k_withMostCentral.root");
    Int_t centbin1 = 0;
    Int_t centbin2 = 0;
    Int_t centbin3 = 0;
    if(minCent1==0)  centbin1 = 0;
    if(minCent1==5)  centbin1 = 1;
    if(minCent1==10) centbin1 = 2;
    if(minCent1==15) centbin1 = 3;
    if(minCent1==20) centbin1 = 4;
    if(minCent1==30) centbin1 = 5;
    if(minCent1==40) centbin1 = 6;
    if(minCent1==50) centbin1 = 7;
    if(minCent1==60) centbin1 = 8;
    if(minCent1==70) centbin1 = 9;
    if(minCent1==80) centbin1 = 10;
    if(minCent1==90) centbin1 = 11;
    if(minCent2==0)  centbin2 = 0;
    if(minCent2==5)  centbin2 = 1;
    if(minCent2==10) centbin2 = 2;
    if(minCent2==15) centbin2 = 3;
    if(minCent2==20) centbin2 = 4;
    if(minCent2==30) centbin2 = 5;
    if(minCent2==40) centbin2 = 6;
    if(minCent2==50) centbin2 = 7;
    if(minCent2==60) centbin2 = 8;
    if(minCent2==70) centbin2 = 9;
    if(minCent2==80) centbin2 = 10;
    if(minCent2==90) centbin2 = 11;
    if(minCent3==0)  centbin3 = 0;
    if(minCent3==5)  centbin3 = 1;
    if(minCent3==10) centbin3 = 2;
    if(minCent3==15) centbin3 = 3;
    if(minCent3==20) centbin3 = 4;
    if(minCent3==30) centbin3 = 5;
    if(minCent3==40) centbin3 = 6;
    if(minCent3==50) centbin3 = 7;
    if(minCent3==60) centbin3 = 8;
    if(minCent3==70) centbin3 = 9;
    if(minCent3==80) centbin3 = 10;
    if(minCent3==90) centbin3 = 11;
    TH2D * fak1 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin1));
    TH2D * fak2 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin2));
    TH2D * fak3 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin3));
    cout<<fak1->GetTitle()<<endl;
    cout<<fak2->GetTitle()<<endl;
    cout<<fak3->GetTitle()<<endl;

    TH1D * fak1a = (TH1D *) fak1->ProjectionY("fak1a08",4,4);
    TH1D * fak1b = (TH1D *) fak1->ProjectionY("fak1b08",5,5);
    TH1D * fak2a = (TH1D *) fak2->ProjectionY("fak2a08",4,4);
    TH1D * fak2b = (TH1D *) fak2->ProjectionY("fak2b08",5,5);
    TH1D * fak3a = (TH1D *) fak3->ProjectionY("fak3a08",4,4);
    TH1D * fak3b = (TH1D *) fak3->ProjectionY("fak3b08",5,5);
    fak1b->Divide(fak1a);
    fak2b->Divide(fak2a);
    fak3b->Divide(fak3a);
    fak1b->SetMarkerColor(kGreen);
    fak2b->SetMarkerColor(kGreen);
    fak3b->SetMarkerColor(kGreen);
    fak1b->SetLineColor(kGreen);
    fak2b->SetLineColor(kGreen);
    fak3b->SetLineColor(kGreen);
    ((TPad *) c->FindObject(Form("%sPad2",c->GetTitle())))->cd();
    fak1b->Draw("same");
    TLegend * fakleg1 = new TLegend(0.6,0.75,0.9,0.87);
    fakleg1->AddEntry(fak1b,"Fake Ratio Pos/Neg","lp");
    fakleg1->Draw();
    ((TPad *) c->FindObject(Form("%sPad4",c->GetTitle())))->cd();
    fak2b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad6",c->GetTitle())))->cd();
    fak3b->Draw("same");
   c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareEta08_16) {
    TString tag1 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5";
    TString tag2 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5";
    int nEP1 = etHF;
    int nEP2 = etHF;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    tag1="NegEta-_"+tag1;
    tag2="PosEta-_"+tag2;
    _g1 =  InputType1(minCent1, maxCent1, 1.6, tag1, EPNames[nEP1],"",nPts1); 
    _g1->SetTitle("-1.6 #leq #eta < -0.8");
    _g2 =  InputType1(minCent1, maxCent1, 1.6, tag2, EPNames[nEP2],"",nPts2); 
    _g2->SetTitle("0.8 #leq #eta < 1.6");
    _g3 =  InputType1(minCent2, maxCent2, 1.6, tag1, EPNames[nEP1],"",nPts3); 
    _g3->SetTitle("-1.6 #leq #eta < -0.8");
    _g4 =  InputType1(minCent2, maxCent2, 1.6, tag2, EPNames[nEP2],"",nPts4); 
    _g4->SetTitle("0.8 #leq #eta < 1.6");
    _g5 =  InputType1(minCent3, maxCent3, 1.6, tag1, EPNames[nEP1],"",nPts5); 
    _g5->SetTitle("-1.6 #leq #eta < -0.8");
    _g6 =  InputType1(minCent3, maxCent3, 1.6, tag2, EPNames[nEP2],"",nPts6); 
    _g6->SetTitle("0.8 #leq #eta < 1.6");
    
    TString cantitle = "CompareEta08_16";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
    TFile * tfeff = new TFile("trkCorrFlow_ampt30k_withMostCentral.root");
    Int_t centbin1 = 0;
    Int_t centbin2 = 0;
    Int_t centbin3 = 0;
    if(minCent1==0)  centbin1 = 0;
    if(minCent1==5)  centbin1 = 1;
    if(minCent1==10) centbin1 = 2;
    if(minCent1==15) centbin1 = 3;
    if(minCent1==20) centbin1 = 4;
    if(minCent1==30) centbin1 = 5;
    if(minCent1==40) centbin1 = 6;
    if(minCent1==50) centbin1 = 7;
    if(minCent1==60) centbin1 = 8;
    if(minCent1==70) centbin1 = 9;
    if(minCent1==80) centbin1 = 10;
    if(minCent1==90) centbin1 = 11;
    if(minCent2==0)  centbin2 = 0;
    if(minCent2==5)  centbin2 = 1;
    if(minCent2==10) centbin2 = 2;
    if(minCent2==15) centbin2 = 3;
    if(minCent2==20) centbin2 = 4;
    if(minCent2==30) centbin2 = 5;
    if(minCent2==40) centbin2 = 6;
    if(minCent2==50) centbin2 = 7;
    if(minCent2==60) centbin2 = 8;
    if(minCent2==70) centbin2 = 9;
    if(minCent2==80) centbin2 = 10;
    if(minCent2==90) centbin2 = 11;
    if(minCent3==0)  centbin3 = 0;
    if(minCent3==5)  centbin3 = 1;
    if(minCent3==10) centbin3 = 2;
    if(minCent3==15) centbin3 = 3;
    if(minCent3==20) centbin3 = 4;
    if(minCent3==30) centbin3 = 5;
    if(minCent3==40) centbin3 = 6;
    if(minCent3==50) centbin3 = 7;
    if(minCent3==60) centbin3 = 8;
    if(minCent3==70) centbin3 = 9;
    if(minCent3==80) centbin3 = 10;
    if(minCent3==90) centbin3 = 11;
    TH2D * fak1 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin1));
    TH2D * fak2 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin2));
    TH2D * fak3 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin3));
    TH1D * fak1a = (TH1D *) fak1->ProjectionY("fak1a16",3,3);
    TH1D * fak1b = (TH1D *) fak1->ProjectionY("fak1b16",6,6);
    TH1D * fak2a = (TH1D *) fak2->ProjectionY("fak2a16",3,3);
    TH1D * fak2b = (TH1D *) fak2->ProjectionY("fak2b16",6,6);
    TH1D * fak3a = (TH1D *) fak3->ProjectionY("fak3a16",3,3);
    TH1D * fak3b = (TH1D *) fak3->ProjectionY("fak3b16",6,6);
    fak1b->Divide(fak1a);
    fak2b->Divide(fak2a);
    fak3b->Divide(fak3a);
    fak1b->SetMarkerColor(kGreen);
    fak2b->SetMarkerColor(kGreen);
    fak3b->SetMarkerColor(kGreen);
    fak1b->SetLineColor(kGreen);
    fak2b->SetLineColor(kGreen);
    fak3b->SetLineColor(kGreen);
    ((TPad *) c->FindObject(Form("%sPad2",c->GetTitle())))->cd();
    TLegend * fakleg1 = new TLegend(0.6,0.75,0.9,0.87);
    fakleg1->AddEntry(fak1b,"Fake Ratio Pos/Neg","lp");
    fakleg1->Draw();
    fak1b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad4",c->GetTitle())))->cd();
    fak2b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad6",c->GetTitle())))->cd();
    fak3b->Draw("same");
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareEta16_20) {
    TString tag1 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_NarrowEtaBins";
    TString tag2 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_NarrowEtaBins";
    //    int nEP1 = etHF;
    //    int nEP2 = etHF;
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    tag1="NegEta-_"+tag1;
    tag2="PosEta-_"+tag2;
    _g1 =  InputType1(minCent1, maxCent1, 2.0, tag1, EPNames[nEP1],"",nPts1); 
    _g1->SetTitle("-2.0 #leq #eta < -1.6");
    _g2 =  InputType1(minCent1, maxCent1, 2.0, tag2, EPNames[nEP2],"",nPts2); 
    _g2->SetTitle("1.6 #leq #eta < 2.0");
    _g3 =  InputType1(minCent2, maxCent2, 2.0, tag1, EPNames[nEP1],"",nPts3); 
    _g3->SetTitle("-2.0 #leq #eta < -1.6");
    _g4 =  InputType1(minCent2, maxCent2, 2.0, tag2, EPNames[nEP2],"",nPts4); 
    _g4->SetTitle("1.6 #leq #eta < 2.0");
    _g5 =  InputType1(minCent3, maxCent3, 2.0, tag1, EPNames[nEP1],"",nPts5); 
    _g5->SetTitle("-2.0 #leq #eta < -1.6");
    _g6 =  InputType1(minCent3, maxCent3, 2.0, tag2, EPNames[nEP2],"",nPts6); 
    _g6->SetTitle("1.6 #leq #eta < 2.0");
    
    TString cantitle = "CompareEta16_20";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
    TFile * tfeff = new TFile("trkCorrFlow_ampt30k_withMostCentral.root");
    Int_t centbin1 = 0;
    Int_t centbin2 = 0;
    Int_t centbin3 = 0;
    if(minCent1==0)  centbin1 = 0;
    if(minCent1==5)  centbin1 = 1;
    if(minCent1==10) centbin1 = 2;
    if(minCent1==15) centbin1 = 3;
    if(minCent1==20) centbin1 = 4;
    if(minCent1==30) centbin1 = 5;
    if(minCent1==40) centbin1 = 6;
    if(minCent1==50) centbin1 = 7;
    if(minCent1==60) centbin1 = 8;
    if(minCent1==70) centbin1 = 9;
    if(minCent1==80) centbin1 = 10;
    if(minCent1==90) centbin1 = 11;
    if(minCent2==0)  centbin2 = 0;
    if(minCent2==5)  centbin2 = 1;
    if(minCent2==10) centbin2 = 2;
    if(minCent2==15) centbin2 = 3;
    if(minCent2==20) centbin2 = 4;
    if(minCent2==30) centbin2 = 5;
    if(minCent2==40) centbin2 = 6;
    if(minCent2==50) centbin2 = 7;
    if(minCent2==60) centbin2 = 8;
    if(minCent2==70) centbin2 = 9;
    if(minCent2==80) centbin2 = 10;
    if(minCent2==90) centbin2 = 11;
    if(minCent3==0)  centbin3 = 0;
    if(minCent3==5)  centbin3 = 1;
    if(minCent3==10) centbin3 = 2;
    if(minCent3==15) centbin3 = 3;
    if(minCent3==20) centbin3 = 4;
    if(minCent3==30) centbin3 = 5;
    if(minCent3==40) centbin3 = 6;
    if(minCent3==50) centbin3 = 7;
    if(minCent3==60) centbin3 = 8;
    if(minCent3==70) centbin3 = 9;
    if(minCent3==80) centbin3 = 10;
    if(minCent3==90) centbin3 = 11;
    TH2D * fak1 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin1));
    TH2D * fak2 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin2));
    TH2D * fak3 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin3));
    TH1D * fak1a = (TH1D *) fak1->ProjectionY("fak1a20",2,2);
    TH1D * fak1b = (TH1D *) fak1->ProjectionY("fak1b20",7,7);
    TH1D * fak2a = (TH1D *) fak2->ProjectionY("fak2a20",2,2);
    TH1D * fak2b = (TH1D *) fak2->ProjectionY("fak2b20",7,7);
    TH1D * fak3a = (TH1D *) fak3->ProjectionY("fak3a20",2,2);
    TH1D * fak3b = (TH1D *) fak3->ProjectionY("fak3b20",7,7);
    fak1b->Divide(fak1a);
    fak2b->Divide(fak2a);
    fak3b->Divide(fak3a);
    fak1b->SetMarkerColor(kGreen);
    fak2b->SetMarkerColor(kGreen);
    fak3b->SetMarkerColor(kGreen);
    fak1b->SetLineColor(kGreen);
    fak2b->SetLineColor(kGreen);
    fak3b->SetLineColor(kGreen);
    ((TPad *) c->FindObject(Form("%sPad2",c->GetTitle())))->cd();
    TLegend * fakleg1 = new TLegend(0.6,0.75,0.9,0.87);
    fakleg1->AddEntry(fak1b,"Fake Ratio Pos/Neg","lp");
    fakleg1->Draw();
    fak1b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad4",c->GetTitle())))->cd();
    fak2b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad6",c->GetTitle())))->cd();
    fak3b->Draw("same");
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }

  if(CompareEta22_24dz5Flat) {
    TString tag1 = "Flow_Skim_Run2010-v5_dz5Flat_-10to10";
    TString tag2 = "Flow_Skim_Run2010-v5_dz5Flat_-10to10";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/%s.root",tag2.Data()),"READ");
    tag1="NegEta-"+tag1;
    tag2="PosEta-"+tag2;
    _g1 =  InputType1(minCent1, maxCent1, 2.0, tag1, EPNames[nEP1],"",nPts1); 
    _g1->SetTitle("-2.4 #leq #eta < -2.2");
    _g2 =  InputType1(minCent1, maxCent1, 2.0, tag2, EPNames[nEP2],"",nPts2); 
    _g2->SetTitle("2.2 #leq #eta < 2.4");
    _g3 =  InputType1(minCent2, maxCent2, 2.0, tag1, EPNames[nEP1],"",nPts3); 
    _g3->SetTitle("-2.4 #leq #eta < -2.2");
    _g4 =  InputType1(minCent2, maxCent2, 2.0, tag2, EPNames[nEP2],"",nPts4); 
    _g4->SetTitle("2.2 #leq #eta < 2.4");
    _g5 =  InputType1(minCent3, maxCent3, 2.0, tag1, EPNames[nEP1],"",nPts5); 
    _g5->SetTitle("-2.4 #leq #eta < -2.2");
    _g6 =  InputType1(minCent3, maxCent3, 2.0, tag2, EPNames[nEP2],"",nPts6); 
    _g6->SetTitle("2.2 #leq #eta < 2.4");
    
    TString cantitle = "CompareEta22_24dz5Flat";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
    TFile * tfeff = new TFile("trkCorrFlow_ampt30k_withMostCentral.root");
    Int_t centbin1 = 0;
    Int_t centbin2 = 0;
    Int_t centbin3 = 0;
    if(minCent1==0)  centbin1 = 0;
    if(minCent1==5)  centbin1 = 1;
    if(minCent1==10) centbin1 = 2;
    if(minCent1==15) centbin1 = 3;
    if(minCent1==20) centbin1 = 4;
    if(minCent1==30) centbin1 = 5;
    if(minCent1==40) centbin1 = 6;
    if(minCent1==50) centbin1 = 7;
    if(minCent1==60) centbin1 = 8;
    if(minCent1==70) centbin1 = 9;
    if(minCent1==80) centbin1 = 10;
    if(minCent1==90) centbin1 = 11;
    if(minCent2==0)  centbin2 = 0;
    if(minCent2==5)  centbin2 = 1;
    if(minCent2==10) centbin2 = 2;
    if(minCent2==15) centbin2 = 3;
    if(minCent2==20) centbin2 = 4;
    if(minCent2==30) centbin2 = 5;
    if(minCent2==40) centbin2 = 6;
    if(minCent2==50) centbin2 = 7;
    if(minCent2==60) centbin2 = 8;
    if(minCent2==70) centbin2 = 9;
    if(minCent2==80) centbin2 = 10;
    if(minCent2==90) centbin2 = 11;
    if(minCent3==0)  centbin3 = 0;
    if(minCent3==5)  centbin3 = 1;
    if(minCent3==10) centbin3 = 2;
    if(minCent3==15) centbin3 = 3;
    if(minCent3==20) centbin3 = 4;
    if(minCent3==30) centbin3 = 5;
    if(minCent3==40) centbin3 = 6;
    if(minCent3==50) centbin3 = 7;
    if(minCent3==60) centbin3 = 8;
    if(minCent3==70) centbin3 = 9;
    if(minCent3==80) centbin3 = 10;
    if(minCent3==90) centbin3 = 11;
    TH2D * fak1 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin1));
    TH2D * fak2 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin2));
    TH2D * fak3 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin3));
    TH1D * fak1a = (TH1D *) fak1->ProjectionY("fak1a20",2,2);
    TH1D * fak1b = (TH1D *) fak1->ProjectionY("fak1b20",7,7);
    TH1D * fak2a = (TH1D *) fak2->ProjectionY("fak2a20",2,2);
    TH1D * fak2b = (TH1D *) fak2->ProjectionY("fak2b20",7,7);
    TH1D * fak3a = (TH1D *) fak3->ProjectionY("fak3a20",2,2);
    TH1D * fak3b = (TH1D *) fak3->ProjectionY("fak3b20",7,7);
    fak1b->Divide(fak1a);
    fak2b->Divide(fak2a);
    fak3b->Divide(fak3a);
    fak1b->SetMarkerColor(kGreen);
    fak2b->SetMarkerColor(kGreen);
    fak3b->SetMarkerColor(kGreen);
    fak1b->SetLineColor(kGreen);
    fak2b->SetLineColor(kGreen);
    fak3b->SetLineColor(kGreen);
    ((TPad *) c->FindObject(Form("%sPad2",c->GetTitle())))->cd();
    TLegend * fakleg1 = new TLegend(0.6,0.75,0.9,0.87);
    fakleg1->AddEntry(fak1b,"Fake Ratio Pos/Neg","lp");
    fakleg1->Draw();
    fak1b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad4",c->GetTitle())))->cd();
    fak2b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad6",c->GetTitle())))->cd();
    fak3b->Draw("same");
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareEta22_24dz10Flat) {
    TString tag1 = "Flow_Skim_Run2010-v5_dz10Flat_-10to10.root";
    TString tag2 = "Flow_Skim_Run2010-v5_dz10Flat_-10to10.root";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    tag1="NegEta-_"+tag1;
    tag2="PosEta-_"+tag2;
    _g1 =  InputType1(minCent1, maxCent1, 2.0, tag1, EPNames[nEP1],"",nPts1); 
    _g1->SetTitle("-2.4 #leq #eta < -2.2");
    _g2 =  InputType1(minCent1, maxCent1, 2.0, tag2, EPNames[nEP2],"",nPts2); 
    _g2->SetTitle("2.2 #leq #eta < 2.4");
    _g3 =  InputType1(minCent2, maxCent2, 2.0, tag1, EPNames[nEP1],"",nPts3); 
    _g3->SetTitle("-2.4 #leq #eta < -2.2");
    _g4 =  InputType1(minCent2, maxCent2, 2.0, tag2, EPNames[nEP2],"",nPts4); 
    _g4->SetTitle("2.2 #leq #eta < 2.4");
    _g5 =  InputType1(minCent3, maxCent3, 2.0, tag1, EPNames[nEP1],"",nPts5); 
    _g5->SetTitle("-2.4 #leq #eta < -2.2");
    _g6 =  InputType1(minCent3, maxCent3, 2.0, tag2, EPNames[nEP2],"",nPts6); 
    _g6->SetTitle("2.2 #leq #eta < 2.4");
    
    TString cantitle = "CompareEta22_24dz10Flat";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
    TFile * tfeff = new TFile("trkCorrFlow_ampt30k_withMostCentral.root");
    Int_t centbin1 = 0;
    Int_t centbin2 = 0;
    Int_t centbin3 = 0;
    if(minCent1==0)  centbin1 = 0;
    if(minCent1==5)  centbin1 = 1;
    if(minCent1==10) centbin1 = 2;
    if(minCent1==15) centbin1 = 3;
    if(minCent1==20) centbin1 = 4;
    if(minCent1==30) centbin1 = 5;
    if(minCent1==40) centbin1 = 6;
    if(minCent1==50) centbin1 = 7;
    if(minCent1==60) centbin1 = 8;
    if(minCent1==70) centbin1 = 9;
    if(minCent1==80) centbin1 = 10;
    if(minCent1==90) centbin1 = 11;
    if(minCent2==0)  centbin2 = 0;
    if(minCent2==5)  centbin2 = 1;
    if(minCent2==10) centbin2 = 2;
    if(minCent2==15) centbin2 = 3;
    if(minCent2==20) centbin2 = 4;
    if(minCent2==30) centbin2 = 5;
    if(minCent2==40) centbin2 = 6;
    if(minCent2==50) centbin2 = 7;
    if(minCent2==60) centbin2 = 8;
    if(minCent2==70) centbin2 = 9;
    if(minCent2==80) centbin2 = 10;
    if(minCent2==90) centbin2 = 11;
    if(minCent3==0)  centbin3 = 0;
    if(minCent3==5)  centbin3 = 1;
    if(minCent3==10) centbin3 = 2;
    if(minCent3==15) centbin3 = 3;
    if(minCent3==20) centbin3 = 4;
    if(minCent3==30) centbin3 = 5;
    if(minCent3==40) centbin3 = 6;
    if(minCent3==50) centbin3 = 7;
    if(minCent3==60) centbin3 = 8;
    if(minCent3==70) centbin3 = 9;
    if(minCent3==80) centbin3 = 10;
    if(minCent3==90) centbin3 = 11;
    TH2D * fak1 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin1));
    TH2D * fak2 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin2));
    TH2D * fak3 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin3));
    TH1D * fak1a = (TH1D *) fak1->ProjectionY("fak1a20",2,2);
    TH1D * fak1b = (TH1D *) fak1->ProjectionY("fak1b20",7,7);
    TH1D * fak2a = (TH1D *) fak2->ProjectionY("fak2a20",2,2);
    TH1D * fak2b = (TH1D *) fak2->ProjectionY("fak2b20",7,7);
    TH1D * fak3a = (TH1D *) fak3->ProjectionY("fak3a20",2,2);
    TH1D * fak3b = (TH1D *) fak3->ProjectionY("fak3b20",7,7);
    fak1b->Divide(fak1a);
    fak2b->Divide(fak2a);
    fak3b->Divide(fak3a);
    fak1b->SetMarkerColor(kGreen);
    fak2b->SetMarkerColor(kGreen);
    fak3b->SetMarkerColor(kGreen);
    fak1b->SetLineColor(kGreen);
    fak2b->SetLineColor(kGreen);
    fak3b->SetLineColor(kGreen);
    ((TPad *) c->FindObject(Form("%sPad2",c->GetTitle())))->cd();
    TLegend * fakleg1 = new TLegend(0.6,0.75,0.9,0.87);
    fakleg1->AddEntry(fak1b,"Fake Ratio Pos/Neg","lp");
    fakleg1->Draw();
    fak1b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad4",c->GetTitle())))->cd();
    fak2b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad6",c->GetTitle())))->cd();
    fak3b->Draw("same");
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareEta16_20vtx25) {
    TString tag1 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_vtx-2.5to2.5";
    TString tag2 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_vtx-2.5to2.5";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    tag1="NegEta-_"+tag1;
    tag2="PosEta-_"+tag2;
    _g1 =  InputType1(minCent1, maxCent1, 2.0, tag1, EPNames[nEP1],"",nPts1); 
    _g1->SetTitle("-2.0 #leq #eta < -1.6");
    _g2 =  InputType1(minCent1, maxCent1, 2.0, tag2, EPNames[nEP2],"",nPts2); 
    _g2->SetTitle("1.6 #leq #eta < 2.0");
    _g3 =  InputType1(minCent2, maxCent2, 2.0, tag1, EPNames[nEP1],"",nPts3); 
    _g3->SetTitle("-2.0 #leq #eta < -1.6");
    _g4 =  InputType1(minCent2, maxCent2, 2.0, tag2, EPNames[nEP2],"",nPts4); 
    _g4->SetTitle("1.6 #leq #eta < 2.0");
    _g5 =  InputType1(minCent3, maxCent3, 2.0, tag1, EPNames[nEP1],"",nPts5); 
    _g5->SetTitle("-2.0 #leq #eta < -1.6");
    _g6 =  InputType1(minCent3, maxCent3, 2.0, tag2, EPNames[nEP2],"",nPts6); 
    _g6->SetTitle("1.6 #leq #eta < 2.0");
    
    TString cantitle = "CompareEta16_20vtx25";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
    TFile * tfeff = new TFile("trkCorrFlow_ampt30k_withMostCentral.root");
    Int_t centbin1 = 0;
    Int_t centbin2 = 0;
    Int_t centbin3 = 0;
    if(minCent1==0)  centbin1 = 0;
    if(minCent1==5)  centbin1 = 1;
    if(minCent1==10) centbin1 = 2;
    if(minCent1==15) centbin1 = 3;
    if(minCent1==20) centbin1 = 4;
    if(minCent1==30) centbin1 = 5;
    if(minCent1==40) centbin1 = 6;
    if(minCent1==50) centbin1 = 7;
    if(minCent1==60) centbin1 = 8;
    if(minCent1==70) centbin1 = 9;
    if(minCent1==80) centbin1 = 10;
    if(minCent1==90) centbin1 = 11;
    if(minCent2==0)  centbin2 = 0;
    if(minCent2==5)  centbin2 = 1;
    if(minCent2==10) centbin2 = 2;
    if(minCent2==15) centbin2 = 3;
    if(minCent2==20) centbin2 = 4;
    if(minCent2==30) centbin2 = 5;
    if(minCent2==40) centbin2 = 6;
    if(minCent2==50) centbin2 = 7;
    if(minCent2==60) centbin2 = 8;
    if(minCent2==70) centbin2 = 9;
    if(minCent2==80) centbin2 = 10;
    if(minCent2==90) centbin2 = 11;
    if(minCent3==0)  centbin3 = 0;
    if(minCent3==5)  centbin3 = 1;
    if(minCent3==10) centbin3 = 2;
    if(minCent3==15) centbin3 = 3;
    if(minCent3==20) centbin3 = 4;
    if(minCent3==30) centbin3 = 5;
    if(minCent3==40) centbin3 = 6;
    if(minCent3==50) centbin3 = 7;
    if(minCent3==60) centbin3 = 8;
    if(minCent3==70) centbin3 = 9;
    if(minCent3==80) centbin3 = 10;
    if(minCent3==90) centbin3 = 11;
    TH2D * fak1 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin1));
    TH2D * fak2 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin2));
    TH2D * fak3 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin3));
    TH1D * fak1a = (TH1D *) fak1->ProjectionY("fak1a20",2,2);
    TH1D * fak1b = (TH1D *) fak1->ProjectionY("fak1b20",7,7);
    TH1D * fak2a = (TH1D *) fak2->ProjectionY("fak2a20",2,2);
    TH1D * fak2b = (TH1D *) fak2->ProjectionY("fak2b20",7,7);
    TH1D * fak3a = (TH1D *) fak3->ProjectionY("fak3a20",2,2);
    TH1D * fak3b = (TH1D *) fak3->ProjectionY("fak3b20",7,7);
    fak1b->Divide(fak1a);
    fak2b->Divide(fak2a);
    fak3b->Divide(fak3a);
    fak1b->SetMarkerColor(kGreen);
    fak2b->SetMarkerColor(kGreen);
    fak3b->SetMarkerColor(kGreen);
    fak1b->SetLineColor(kGreen);
    fak2b->SetLineColor(kGreen);
    fak3b->SetLineColor(kGreen);
    ((TPad *) c->FindObject(Form("%sPad2",c->GetTitle())))->cd();
    TLegend * fakleg1 = new TLegend(0.6,0.75,0.9,0.87);
    fakleg1->AddEntry(fak1b,"Fake Ratio Pos/Neg","lp");
    fakleg1->Draw();
    fak1b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad4",c->GetTitle())))->cd();
    fak2b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad6",c->GetTitle())))->cd();
    fak3b->Draw("same");
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareEta20_24) {
    TString tag1 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_NarrowEtaBins";
    TString tag2 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_NarrowEtaBins";
    //    int nEP1 = etHF;
    //    int nEP2 = etHF;
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    tag1="NegEta-_"+tag1;
    tag2="PosEta-_"+tag2;
    _g1 =  InputType1(minCent1, maxCent1, 2.4, tag1, EPNames[nEP1],"",nPts1); 
    _g1->SetTitle("-2.4 #leq #eta < -2.0");
    _g2 =  InputType1(minCent1, maxCent1, 2.4, tag2, EPNames[nEP2],"",nPts2); 
    _g2->SetTitle("2.0 #leq #eta < 2.4");
    _g3 =  InputType1(minCent2, maxCent2, 2.4, tag1, EPNames[nEP1],"",nPts3); 
    _g3->SetTitle("-2.4 #leq #eta < -2.0");
    _g4 =  InputType1(minCent2, maxCent2, 2.4, tag2, EPNames[nEP2],"",nPts4); 
    _g4->SetTitle("2.0 #leq #eta <2.4");
    _g5 =  InputType1(minCent3, maxCent3, 2.4, tag1, EPNames[nEP1],"",nPts5); 
    _g5->SetTitle("-2.4 #leq #eta <-2.0");
    _g6 =  InputType1(minCent3, maxCent3, 2.4, tag2, EPNames[nEP2],"",nPts6); 
    _g6->SetTitle("2.0 #leq #eta < 2.4");
    
    TString cantitle = "Compare20_24";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
     TFile * tfeff = new TFile("trkCorrFlow_ampt30k_withMostCentral.root");
    Int_t centbin1 = 0;
    Int_t centbin2 = 0;
    Int_t centbin3 = 0;
    if(minCent1==0)  centbin1 = 0;
    if(minCent1==5)  centbin1 = 1;
    if(minCent1==10) centbin1 = 2;
    if(minCent1==15) centbin1 = 3;
    if(minCent1==20) centbin1 = 4;
    if(minCent1==30) centbin1 = 5;
    if(minCent1==40) centbin1 = 6;
    if(minCent1==50) centbin1 = 7;
    if(minCent1==60) centbin1 = 8;
    if(minCent1==70) centbin1 = 9;
    if(minCent1==80) centbin1 = 10;
    if(minCent1==90) centbin1 = 11;
    if(minCent2==0)  centbin2 = 0;
    if(minCent2==5)  centbin2 = 1;
    if(minCent2==10) centbin2 = 2;
    if(minCent2==15) centbin2 = 3;
    if(minCent2==20) centbin2 = 4;
    if(minCent2==30) centbin2 = 5;
    if(minCent2==40) centbin2 = 6;
    if(minCent2==50) centbin2 = 7;
    if(minCent2==60) centbin2 = 8;
    if(minCent2==70) centbin2 = 9;
    if(minCent2==80) centbin2 = 10;
    if(minCent2==90) centbin2 = 11;
    if(minCent3==0)  centbin3 = 0;
    if(minCent3==5)  centbin3 = 1;
    if(minCent3==10) centbin3 = 2;
    if(minCent3==15) centbin3 = 3;
    if(minCent3==20) centbin3 = 4;
    if(minCent3==30) centbin3 = 5;
    if(minCent3==40) centbin3 = 6;
    if(minCent3==50) centbin3 = 7;
    if(minCent3==60) centbin3 = 8;
    if(minCent3==70) centbin3 = 9;
    if(minCent3==80) centbin3 = 10;
    if(minCent3==90) centbin3 = 11;
    TH2D * fak1 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin1));
    TH2D * fak2 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin2));
    TH2D * fak3 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin3));
    TH1D * fak1a = (TH1D *) fak1->ProjectionY("fak1a24",1,1);
    TH1D * fak1b = (TH1D *) fak1->ProjectionY("fak1b24",8,8);
    TH1D * fak2a = (TH1D *) fak2->ProjectionY("fak2a24",1,1);
    TH1D * fak2b = (TH1D *) fak2->ProjectionY("fak2b24",8,8);
    TH1D * fak3a = (TH1D *) fak3->ProjectionY("fak3a24",1,1);
    TH1D * fak3b = (TH1D *) fak3->ProjectionY("fak3b24",8,8);
    fak1b->Divide(fak1a);
    fak2b->Divide(fak2a);
    fak3b->Divide(fak3a);
    fak1b->SetMarkerColor(kGreen);
    fak2b->SetMarkerColor(kGreen);
    fak3b->SetMarkerColor(kGreen);
    fak1b->SetLineColor(kGreen);
    fak2b->SetLineColor(kGreen);
    fak3b->SetLineColor(kGreen);
    ((TPad *) c->FindObject(Form("%sPad2",c->GetTitle())))->cd();
     TLegend * fakleg1 = new TLegend(0.6,0.75,0.9,0.87);
    fakleg1->AddEntry(fak1b,"Fake Ratio Pos/Neg","lp");
    fakleg1->Draw();
   fak1b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad4",c->GetTitle())))->cd();
    fak2b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad6",c->GetTitle())))->cd();
    fak3b->Draw("same");
   c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareEta20_24vtx25) {
    TString tag1 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_vtx-2.5to2.5";
    TString tag2 = "hiGoodMergedTracks_Flow_Skim_Run2010-v5_vtx-2.5to2.5";
   //    int nEP1 = etHF;
    //    int nEP2 = etHF;
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    tag1="NegEta-_"+tag1;
    tag2="PosEta-_"+tag2;
    _g1 =  InputType1(minCent1, maxCent1, 2.4, tag1, EPNames[nEP1],"",nPts1); 
    _g1->SetTitle("-2.4 #leq #eta < -2.0");
    _g2 =  InputType1(minCent1, maxCent1, 2.4, tag2, EPNames[nEP2],"",nPts2); 
    _g2->SetTitle("2.0 #leq #eta < 2.4");
    _g3 =  InputType1(minCent2, maxCent2, 2.4, tag1, EPNames[nEP1],"",nPts3); 
    _g3->SetTitle("-2.4 #leq #eta < -2.0");
    _g4 =  InputType1(minCent2, maxCent2, 2.4, tag2, EPNames[nEP2],"",nPts4); 
    _g4->SetTitle("2.0 #leq #eta <2.4");
    _g5 =  InputType1(minCent3, maxCent3, 2.4, tag1, EPNames[nEP1],"",nPts5); 
    _g5->SetTitle("-2.4 #leq #eta <-2.0");
    _g6 =  InputType1(minCent3, maxCent3, 2.4, tag2, EPNames[nEP2],"",nPts6); 
    _g6->SetTitle("2.0 #leq #eta < 2.4");
    
    TString cantitle = "Compare20_24vtx25";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,-1,-1,nEP2,3);
     TFile * tfeff = new TFile("trkCorrFlow_ampt30k_withMostCentral.root");
    Int_t centbin1 = 0;
    Int_t centbin2 = 0;
    Int_t centbin3 = 0;
    if(minCent1==0)  centbin1 = 0;
    if(minCent1==5)  centbin1 = 1;
    if(minCent1==10) centbin1 = 2;
    if(minCent1==15) centbin1 = 3;
    if(minCent1==20) centbin1 = 4;
    if(minCent1==30) centbin1 = 5;
    if(minCent1==40) centbin1 = 6;
    if(minCent1==50) centbin1 = 7;
    if(minCent1==60) centbin1 = 8;
    if(minCent1==70) centbin1 = 9;
    if(minCent1==80) centbin1 = 10;
    if(minCent1==90) centbin1 = 11;
    if(minCent2==0)  centbin2 = 0;
    if(minCent2==5)  centbin2 = 1;
    if(minCent2==10) centbin2 = 2;
    if(minCent2==15) centbin2 = 3;
    if(minCent2==20) centbin2 = 4;
    if(minCent2==30) centbin2 = 5;
    if(minCent2==40) centbin2 = 6;
    if(minCent2==50) centbin2 = 7;
    if(minCent2==60) centbin2 = 8;
    if(minCent2==70) centbin2 = 9;
    if(minCent2==80) centbin2 = 10;
    if(minCent2==90) centbin2 = 11;
    if(minCent3==0)  centbin3 = 0;
    if(minCent3==5)  centbin3 = 1;
    if(minCent3==10) centbin3 = 2;
    if(minCent3==15) centbin3 = 3;
    if(minCent3==20) centbin3 = 4;
    if(minCent3==30) centbin3 = 5;
    if(minCent3==40) centbin3 = 6;
    if(minCent3==50) centbin3 = 7;
    if(minCent3==60) centbin3 = 8;
    if(minCent3==70) centbin3 = 9;
    if(minCent3==80) centbin3 = 10;
    if(minCent3==90) centbin3 = 11;
    TH2D * fak1 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin1));
    TH2D * fak2 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin2));
    TH2D * fak3 = (TH2D *) tfeff->Get(Form("rFak_cbin%d",centbin3));
    TH1D * fak1a = (TH1D *) fak1->ProjectionY("fak1a24",1,1);
    TH1D * fak1b = (TH1D *) fak1->ProjectionY("fak1b24",8,8);
    TH1D * fak2a = (TH1D *) fak2->ProjectionY("fak2a24",1,1);
    TH1D * fak2b = (TH1D *) fak2->ProjectionY("fak2b24",8,8);
    TH1D * fak3a = (TH1D *) fak3->ProjectionY("fak3a24",1,1);
    TH1D * fak3b = (TH1D *) fak3->ProjectionY("fak3b24",8,8);
    fak1b->Divide(fak1a);
    fak2b->Divide(fak2a);
    fak3b->Divide(fak3a);
    fak1b->SetMarkerColor(kGreen);
    fak2b->SetMarkerColor(kGreen);
    fak3b->SetMarkerColor(kGreen);
    fak1b->SetLineColor(kGreen);
    fak2b->SetLineColor(kGreen);
    fak3b->SetLineColor(kGreen);
    ((TPad *) c->FindObject(Form("%sPad2",c->GetTitle())))->cd();
     TLegend * fakleg1 = new TLegend(0.6,0.75,0.9,0.87);
    fakleg1->AddEntry(fak1b,"Fake Ratio Pos/Neg","lp");
    fakleg1->Draw();
   fak1b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad4",c->GetTitle())))->cd();
    fak2b->Draw("same");
    ((TPad *) c->FindObject(Form("%sPad6",c->GetTitle())))->cd();
    fak3b->Draw("same");
   c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareLowPtCut) {
    TString tag1 = "hiGoodMergedTracks_02_500PtCut_PtWeight";
    TString tag2 = "hiGoodMergedTracks_03_500PtCut_PtWeight";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g1->SetTitle("0.2 - 500 GeV/c");
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g2->SetTitle("0.3 - 500 GeV/c");
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g3->SetTitle("0.2 - 500 GeV/c");
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g4->SetTitle("0.3 - 500 GeV/c");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g5->SetTitle("0.2 - 500 GeV/c");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g6->SetTitle("0.3 - 500 GeV/c");
    
    TString cantitle = "CompareLowPtCut";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare500PtCut) {
    TString tag1 = "hiGoodMergedTracks_03_500PtCut_PtWeight";
    TString tag2 = "hiGoodMergedTracks_03_30PtCut_PtWeight";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g1->SetTitle("0.3 - 500 GeV/c");
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g2->SetTitle("0.3 - 30 GeV/c");
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g3->SetTitle("0.3 - 500 GeV/c");
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g4->SetTitle("0.3 - 30 GeV/c");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g5->SetTitle("0.3 - 500 GeV/c");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g6->SetTitle("0.3 - 30 GeV/c");
    
    TString cantitle = "Compare500PtCut";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare30PtCut) {
    TString tag1 = "hiGoodMergedTracks_03_30PtCut_PtWeight";
    TString tag2 = "hiGoodMergedTracks_03_30PtCut_PtWeight";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g1->SetTitle("0.3 - 3.0 GeV/c");
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g2->SetTitle("0.3 - 3.0 GeV/c");
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g3->SetTitle("0.3 - 3.0 GeV/c");
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g4->SetTitle("0.3 - 3.0 GeV/c");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g5->SetTitle("0.3 - 3.0 GeV/c");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g6->SetTitle("0.3 - 3.0 GeV/c");
    
    TString cantitle = "Compare30PtCut";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare26PtCut) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight";
    TString tag2 = "hiGoodMergedTracks_03_30PtCut_PtWeight";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g1->SetTitle("0.3 - 2.6 GeV/c");
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g2->SetTitle("0.3 - 3.0 GeV/c");
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g3->SetTitle("0.3 - 2.6 GeV/c");
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g4->SetTitle("0.3 - 3.0 GeV/c");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g5->SetTitle("0.3 - 2.6 GeV/c");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g6->SetTitle("0.3 - 3.0 GeV/c");
    
    TString cantitle = "Compare26PtCut";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare25PtCut26PtCut) {
    TString tag1 = "hiGoodMergedTracks_03_25PtCut_PtWeight";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g1->SetTitle("0.3 - 2.5 GeV/c");
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g2->SetTitle("0.3 - 2.6 GeV/c");
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g3->SetTitle("0.3 - 2.5 GeV/c");
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g4->SetTitle("0.3 - 2.6 GeV/c");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g5->SetTitle("0.3 - 2.5 GeV/c");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g6->SetTitle("0.3 - 2.6 GeV/c");
    
    TString cantitle = "Compare26PtCut";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare22PtCut) {
    TString tag1 = "hiGoodMergedTracks_03_22PtCut_PtWeight";
    TString tag2 = "hiGoodMergedTracks_03_30PtCut_PtWeight";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g1->SetTitle("0.3 - 2.2 GeV/c");
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g2->SetTitle("0.3 - 3.0 GeV/c");
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g3->SetTitle("0.3 - 2.2 GeV/c");
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g4->SetTitle("0.3 - 3.0 GeV/c");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g5->SetTitle("0.3 - 2.2 GeV/c");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g6->SetTitle("0.3 - 3.0 GeV/c");
    
    TString cantitle = "Compare22PtCut";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare18PtCut) {
    TString tag1 = "hiGoodMergedTracks_03_18PtCut_PtWeight";
    TString tag2 = "hiGoodMergedTracks_03_30PtCut_PtWeight";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g1->SetTitle("0.3 - 1.8 GeV/c");
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g2->SetTitle("0.3 - 3.0 GeV/c");
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g3->SetTitle("0.3 - 1.8 GeV/c");
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g4->SetTitle("0.3 - 3.0 GeV/c");
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g5->SetTitle("0.3 - 1.8 GeV/c");
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g6->SetTitle("0.3 - 3.0 GeV/c");
    
    TString cantitle = "Compare18PtCut";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare25Gap) {
    _g1 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_25Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g1->SetTitle("0-5\% 0.25 gap");
    _g2 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g2->SetTitle("0-5\% 0.25 gap");
    if(nPts1 != nPts2) cout<<"WARNING POINT MISMATCH: "<<nPts1<<" "<<nPts2<<endl;
    _g3 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_25Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g3->SetTitle("10-15\% 0.25 gap");
    _g4 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g4->SetTitle("10-15\% 0.25 gap");
    if(nPts3 != nPts4) cout<<"WARNING POINT MISMATCH: "<<nPts3<<" "<<nPts4<<endl;
    _g5 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_25Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g5->SetTitle("40-50\% 0.25 gap");
    _g6 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g6->SetTitle("40-50\% 0.25 gap");
    if(nPts5 != nPts6) cout<<"WARNING POINT MISMATCH: "<<nPts5<<" "<<nPts6<<endl;
    

    TString cantitle = "Compare25Gap";
    TCanvas * c = template(cantitle,ylabel,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare375Gap) {
    _g1 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_375Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g1->SetTitle("0-5\% 0.375 gap");
    _g2 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g2->SetTitle("0-5\% 0.25 gap");
    if(nPts1 != nPts2) cout<<"WARNING POINT MISMATCH: "<<nPts1<<" "<<nPts2<<endl;
    _g3 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_375Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g3->SetTitle("10-15\% 0.375 gap");
    _g4 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g4->SetTitle("10-15\% 0.25 gap");
    if(nPts3 != nPts4) cout<<"WARNING POINT MISMATCH: "<<nPts3<<" "<<nPts4<<endl;
    _g5 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_375Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g5->SetTitle("40-50\% 0.375 gap");
    _g6 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g6->SetTitle("40-50\% 0.25 gap");
    if(nPts5 != nPts6) cout<<"WARNING POINT MISMATCH: "<<nPts5<<" "<<nPts6<<endl;
    

    TString cantitle = "Compare375Gap";
    TCanvas * c = template(cantitle,ylabel,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare500Gap) {
    _g1 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_500Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g1->SetTitle("0-5\% 0.50 gap");
    _g2 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g2->SetTitle("0-5\% 0.25 gap");
    if(nPts1 != nPts2) cout<<"WARNING POINT MISMATCH: "<<nPts1<<" "<<nPts2<<endl;
    _g3 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_500Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g3->SetTitle("10-15\% 0.50 gap");
    _g4 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g4->SetTitle("10-15\% 0.25 gap");
    if(nPts3 != nPts4) cout<<"WARNING POINT MISMATCH: "<<nPts3<<" "<<nPts4<<endl;
    _g5 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_500Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g5->SetTitle("40-50\% 0.50 gap");
    _g6 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g6->SetTitle("40-50\% 0.25 gap");
    if(nPts5 != nPts6) cout<<"WARNING POINT MISMATCH: "<<nPts5<<" "<<nPts6<<endl;
    

    TString cantitle = "Compare500Gap";
    TCanvas * c = template(cantitle,ylabel,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare625Gap) {
    _g1 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_625Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g1->SetTitle("0-5\% 0.625 gap");
    _g2 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g2->SetTitle("0-5\% 0.25 gap");
    if(nPts1 != nPts2) cout<<"WARNING POINT MISMATCH: "<<nPts1<<" "<<nPts2<<endl;
    _g3 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_625Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g3->SetTitle("10-15\% 0.625 gap");
    _g4 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g4->SetTitle("10-15\% 0.25 gap");
    if(nPts3 != nPts4) cout<<"WARNING POINT MISMATCH: "<<nPts3<<" "<<nPts4<<endl;
    _g5 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_625Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g5->SetTitle("40-50\% 0.625 gap");
    _g6 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g6->SetTitle("40-50\% 0.25 gap");
    if(nPts5 != nPts6) cout<<"WARNING POINT MISMATCH: "<<nPts5<<" "<<nPts6<<endl;
    

    TString cantitle = "Compare625Gap";
    TCanvas * c = template(cantitle,ylabel,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }

  if(Compare750Gap) {
    _g1 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_750Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g1->SetTitle("0-5\% 0.750 gap");
    _g2 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g2->SetTitle("0-5\% 0.25 gap");
    if(nPts1 != nPts2) cout<<"WARNING POINT MISMATCH: "<<nPts1<<" "<<nPts2<<endl;
    _g3 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_750Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g3->SetTitle("10-15\% 0.750 gap");
    _g4 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g4->SetTitle("10-15\% 0.25 gap");
    if(nPts3 != nPts4) cout<<"WARNING POINT MISMATCH: "<<nPts3<<" "<<nPts4<<endl;
    _g5 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_750Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g5->SetTitle("40-50\% 0.750 gap");
    _g6 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g6->SetTitle("40-50\% 0.25 gap");
    if(nPts5 != nPts6) cout<<"WARNING POINT MISMATCH: "<<nPts5<<" "<<nPts6<<endl;
    

    TString cantitle = "Compare750Gap";
    TCanvas * c = template(cantitle,ylabel,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare875Gap) {
    _g1 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_875Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g1->SetTitle("0-5\% 0.875 Gap");
    _g2 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g2->SetTitle("0-5\% 0.25 gap");
    if(nPts1 != nPts2) cout<<"WARNING POINT MISMATCH: "<<nPts1<<" "<<nPts2<<endl;
    _g3 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_875Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g3->SetTitle("10-15\% 0.875 gap");
    _g4 = InputType1("results/v2pt_EP_10-15_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g4->SetTitle("10-15\% 0.25 gap");
    if(nPts3 != nPts4) cout<<"WARNING POINT MISMATCH: "<<nPts3<<" "<<nPts4<<endl;
    _g5 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_875Gap_EPTracksPosEtaBigGap_EPTracksNegEtaBigGap.txt",nPts1);
    _g5->SetTitle("40-50\% 0.875 gap");
    _g6 = InputType1("results/v2pt_EP_40-50_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
    _g6->SetTitle("40-50\% 0.25 gap");
    if(nPts5 != nPts6) cout<<"WARNING POINT MISMATCH: "<<nPts5<<" "<<nPts6<<endl;
    

    TString cantitle = "Compare875Gap";
    TCanvas * c = template(cantitle,ylabel,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareETHF) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight";
    int nEP1 = etHFp;
    int nEP2 = etHFm;
    int nEP3 = EvtPTracksPosEtaGap;
    int nEP4 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP3],EPNames[nEP4],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP3],EPNames[nEP4],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP3],EPNames[nEP4],nPts6); 
    _g1->SetTitle("etHF*");
    _g2->SetTitle("EvtPTracks*EtaGap");
    _g3->SetTitle("etHF*");
    _g4->SetTitle("EvtPTracks*EtaGap");
    _g5->SetTitle("etHF*");
    _g6->SetTitle("EvtPTracks*EtaGap");
    
    TString cantitle = "CompareETHF";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP3,nEP4,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare00GapCenter) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_00GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("#Delta #eta > 0.0");
    _g2->SetTitle("#Delta #eta > 0.2");
    _g3->SetTitle("#Delta #eta > 0.0");
    _g4->SetTitle("#Delta #eta > 0.2");
    _g5->SetTitle("#Delta #eta > 0.0");
    _g6->SetTitle("#Delta #eta > 0.2");
    
    TString cantitle = "Compare00GapCenter";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare20GapCenter) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("#Delta #eta > 0.2");
    _g2->SetTitle("#Delta #eta > 0.2");
    _g3->SetTitle("#Delta #eta > 0.2");
    _g4->SetTitle("#Delta #eta > 0.2");
    _g5->SetTitle("#Delta #eta > 0.2");
    _g6->SetTitle("#Delta #eta > 0.2");
    
    TString cantitle = "Compare20GapCenter";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
 
   _g2 = InputType1("results/v2pt_EP_0-5_08-_hiGoodMergedTracks_03_26PtCut_PtWeight_EvtPTracksPosEtaGap_EvtPTracksNegEtaGap.txt",nPts2);
  if(Compare20GapCenter25Gap) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    int nEP3 = EvtPTracksPosEtaGap;
    int nEP4 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP3],EPNames[nEP4],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP3],EPNames[nEP4],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP3],EPNames[nEP4],nPts6); 
    _g1->SetTitle("#Delta #eta > 0.2");
    _g2->SetTitle("#Delta #eta > 0.25");
    _g3->SetTitle("#Delta #eta > 0.2");
    _g4->SetTitle("#Delta #eta > 0.25");
    _g5->SetTitle("#Delta #eta > 0.2");
    _g6->SetTitle("#Delta #eta > 0.25");
    
    TString cantitle = "Compare20GapCenter25Gap";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP3,nEP4,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare50GapCenter25Gap) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_50GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    int nEP3 = EvtPTracksPosEtaGap;
    int nEP4 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP3],EPNames[nEP4],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP3],EPNames[nEP4],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP3],EPNames[nEP4],nPts6); 
    _g1->SetTitle("3 #Delta #eta = 1 subevents, 0.5 gap");
    _g2->SetTitle("EvtPTracks*EtaGap");
    _g3->SetTitle("3 #Delta #eta = 1 subevents, 0.5 gap");
    _g4->SetTitle("EvtPTracks*EtaGap");
    _g5->SetTitle("3 #Delta #eta = 1 subevents, 0.5 gap");
    _g6->SetTitle("EvtPTracks*EtaGap");
    
    TString cantitle = "Compare50GapCenter25Gap";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP3,nEP4,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare40GapCenter) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_40GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("#Delta #eta > 0.4");
    _g2->SetTitle("#Delta #eta > 0.2");
    _g3->SetTitle("#Delta #eta > 0.4");
    _g4->SetTitle("#Delta #eta > 0.2");
    _g5->SetTitle("#Delta #eta > 0.4");
    _g6->SetTitle("#Delta #eta > 0.2");
    
    TString cantitle = "Compare40GapCenter";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare50GapCenter) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_50GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("#Delta #eta > 0.5");
    _g2->SetTitle("#Delta #eta > 0.2");
    _g3->SetTitle("#Delta #eta > 0.5");
    _g4->SetTitle("#Delta #eta > 0.2");
    _g5->SetTitle("#Delta #eta > 0.5");
    _g6->SetTitle("#Delta #eta > 0.2");
    
    TString cantitle = "Compare50GapCenter";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare60GapCenter) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_60GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("#Delta #eta > 0.6");
    _g2->SetTitle("#Delta #eta > 0.2");
    _g3->SetTitle("#Delta #eta > 0.6");
    _g4->SetTitle("#Delta #eta > 0.2");
    _g5->SetTitle("#Delta #eta > 0.6");
    _g6->SetTitle("#Delta #eta > 0.2");
    
    TString cantitle = "Compare60GapCenter";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare80GapCenter) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_80GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("#Delta #eta > 0.8");
    _g2->SetTitle("#Delta #eta > 0.2");
    _g3->SetTitle("#Delta #eta > 0.8");
    _g4->SetTitle("#Delta #eta > 0.2");
    _g5->SetTitle("#Delta #eta > 0.8");
    _g6->SetTitle("#Delta #eta > 0.2");
    
    TString cantitle = "Compare80GapCenter";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare100GapCenter) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_100GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("#Delta #eta > 1.0");
    _g2->SetTitle("#Delta #eta > 0.2");
    _g3->SetTitle("#Delta #eta > 1.0");
    _g4->SetTitle("#Delta #eta > 0.2");
    _g5->SetTitle("#Delta #eta > 1.0");
    _g6->SetTitle("#Delta #eta > 0.2");
    
    TString cantitle = "Compare100GapCenter";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(Compare120GapCenter) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_120GapCenter";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_20GapCenter";
    int nEP1 = EPTracksPosEtaBigGap;
    int nEP2 = EPTracksNegEtaBigGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("#Delta #eta > 1.2");
    _g2->SetTitle("#Delta #eta > 0.2");
    _g3->SetTitle("#Delta #eta > 1.2");
    _g4->SetTitle("#Delta #eta > 0.2");
    _g5->SetTitle("#Delta #eta > 1.2");
    _g6->SetTitle("#Delta #eta > 0.2");
    
    TString cantitle = "Compare120GapCenter";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareNewFlatCentCuts) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_50GapCenter_NewFlatCentCuts";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_50GapCenter";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("with 15\% cent cut");
    _g2->SetTitle("w/o 15\% cent cut");
    _g3->SetTitle("with 15\% cent cut");
    _g4->SetTitle("w/o 15\% cent cut");
    _g5->SetTitle("with 15\% cent cut");
    _g6->SetTitle("w/o 15\% cent cut");
    
    TString cantitle = "CompareNewFlatCentCuts";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareFlatOrder4) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_50GapCenter_NewFlatCentCuts_FlatOrder4";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_50GapCenter_NewFlatCentCuts";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("flat order 4");
    _g2->SetTitle("flat order 21");
    _g3->SetTitle("flat order 4");
    _g4->SetTitle("flat order 21");
    _g5->SetTitle("flat order 4");
    _g6->SetTitle("flat order 21");
    
    TString cantitle = "CompareFlatOrder4";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareNoFlattening) {
    TString tag1 = "hiGoodMergedTracks_03_26PtCut_PtWeight_50GapCenter_NoFlattening";
    TString tag2 = "hiGoodMergedTracks_03_26PtCut_PtWeight_50GapCenter_NewFlatCentCuts";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8,   tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8,   tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8,  tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8,  tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("No Flattening");
    _g2->SetTitle("flat order 21");
    _g3->SetTitle("No Flattening");
    _g4->SetTitle("flat order 21");
    _g5->SetTitle("No Flattening");
    _g6->SetTitle("flat order 21");
    
    TString cantitle = "CompareNoFlattening";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,nEP1,nEP2,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareAMPTOrganwithGen) {
    TString tag1 = "hiGoodMergedTracks_AMPT_Organ_MinBias_2760";
    TString tag2 = "hiGoodMergedTracks_AMPT_Organ_MinBias_2760_GENERATOR";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("AMPT Organ");
    _g2->SetTitle("AMPT Organ Gen");
    _g3->SetTitle("AMPT Organ");
    _g4->SetTitle("AMPT Organ Gen");
    _g5->SetTitle("AMPT Organ");
    _g6->SetTitle("AMPT Organ Gen");
    
    TString cantitle = "CompareAMPTOrganwithGen";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,-1,-1,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }
  if(CompareHydjetBasswithGen) {
    TString tag1 = "hiGoodMergedTracks_Hydjet_Bass_MinBias_2760";
    TString tag2 = "hiGoodMergedTracks_Hydjet_Bass_MinBias_2760_GENERATOR";
    int nEP1 = EvtPTracksPosEtaGap;
    int nEP2 = EvtPTracksNegEtaGap;
    Rescor1 = new TFile(Form("rescor/_%s.root",tag1.Data()),"READ");
    Rescor2 = new TFile(Form("rescor/_%s.root",tag2.Data()),"READ");
    _g1 =  InputType1(minCent1, maxCent1, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts1); 
    _g2 =  InputType1(minCent1, maxCent1, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts2); 
    _g3 =  InputType1(minCent2, maxCent2, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts3); 
    _g4 =  InputType1(minCent2, maxCent2, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts4); 
    _g5 =  InputType1(minCent3, maxCent3, 0.8, tag1, EPNames[nEP1],EPNames[nEP2],nPts5); 
    _g6 =  InputType1(minCent3, maxCent3, 0.8, tag2, EPNames[nEP1],EPNames[nEP2],nPts6); 
    _g1->SetTitle("Hydjet Bass");
    _g2->SetTitle("Hydjet Bass Gen");
    _g3->SetTitle("Hydjet Bass");
    _g4->SetTitle("Hydjet Bass Gen");
    _g5->SetTitle("Hydjet Bass");
    _g6->SetTitle("Hydjet Bass Gen");
    
    TString cantitle = "CompareHydjetBasswithGen";
    TCanvas * c = template(cantitle,ylabel,label1,label2,label3,nEP1,nEP2,-1,-1,3);
    c->Print(Form("compare/png/%s.png",cantitle.Data()),"png");
    c->Print(Form("compare/ps/%s.ps",cantitle.Data()),"Portrait");
  }

}

TGraphErrors * InputType1(TString fileName, Int_t &Num){
  FILE * fin = fopen(fileName.Data(),"r");
  Double_t x[100];
  Double_t y[100];
  Double_t dy[100];
  Num = 0;
  if(fin==NULL) {
    cout<<"File not found: "<<fileName.Data()<<endl;
    return 0;
  }
  char buf[80];
  fgets(buf,80,fin);
  while(fgets(buf,80,fin)!=NULL) {
    if(buf[0]=='_') continue;
    if(sscanf(buf,"%lf\t%lf\t%lf",&x[Num],&y[Num],&dy[Num]) == 3) {
      ++Num;
    } else {
      cout<<"Failed to interpret: "<<buf<<endl;
    };

  }
  if(Num==0) return 0;
  TGraphErrors * g = new TGraphErrors(Num,x,y,0,dy);
  g->SetName(fileName.Data());
  g->SetTitle(fileName.Data());
  return g;
}
TCanvas *  template(TString cantitle, TString ylabel, TString label1, TString label2, TString label3, int nEP1, int nEP2, int nEP3, int nEP4,  Int_t nCompare){
  Double_t LabelSize = 0.05;
  Double_t TitleSize = 0.06;
  Double_t YTitleOffset_2Panel = 0.8;
  Double_t YTitleOffset_4Panel = 1.0;
  Double_t YTitleOffset_6Panel = 1.4;
  TCanvas * c;
  TString stitle1;
  TString stitle2;
  TString stitle3;
  TString rtitle1;
  TString rtitle2;
  TString rtitle3;
  rtitle1 = Form("#frac{%s}{%s}",_g1->GetTitle(),_g2->GetTitle());

  if(nCompare == 1 ) {
    c = new TCanvas(cantitle.Data(),cantitle.Data(),1000,800);
  } else if (nCompare == 2) {
    c = new TCanvas(cantitle.Data(),cantitle.Data(),1400,800);
  } else if (nCompare == 3) {
    c = new TCanvas(cantitle.Data(),cantitle.Data(),1700,800);
  }
  c->cd();
  TPad * PadA = new TPad(Form("%sPadA",cantitle.Data()),Form("%sPadA",cantitle.Data()),0,0,0.75,1,-1,0,0);
  PadA->Draw();
  TPad * PadB = new TPad(Form("%sPadB",cantitle.Data()),Form("%sPadB",cantitle.Data()),0.75,0.0,1,0.5,-1,0,0);
  PadB->Draw();
  TPad * PadC = new TPad(Form("%sPadC",cantitle.Data()),Form("%sPadC",cantitle.Data()),0.75,0.5,1,1.0,-1,0,0);
  PadC->Draw();
  PadA->cd();
  //PadA->Draw();
  if(nCompare == 1 ){
    stitle1 = _hrefA->GetTitle();
    TPad * pad1 = new TPad(Form("%sPad1",cantitle.Data()),Form("%sPad1",cantitle.Data()),0.005,0.5,0.995,0.995,-1,0,0);
    pad1->Draw();
    pad1->SetBottomMargin(0.027);
    pad1->SetGrid(1,1);
    pad1->SetLeftMargin(0.16);
    //c->cd(); 
    TPad * pad2 = new TPad(Form("%sPad2",cantitle.Data()),Form("%sPad2",cantitle.Data()),0.005,0.005,0.995,0.495,-1,0,0);
    pad2->Draw();
    pad2->SetTopMargin(0.0);
    pad2->SetBottomMargin(0.2);
    pad2->SetLeftMargin(0.16);
    pad2->SetGrid(1,1);
  } else if (nCompare == 2) { 
    stitle2 = _hrefB->GetTitle();
    TPad * pad1 = new TPad(Form("%sPad1",cantitle.Data()),Form("%sPad1",cantitle.Data()),0.005,0.5,0.495,0.995,-1,0,0);
    pad1->Draw();
    pad1->SetLeftMargin(0.22);
    pad1->SetRightMargin(0.02);
    pad1->SetBottomMargin(0.027);
    pad1->SetGrid(1,1);
    //c->cd(); 
    TPad * pad2 = new TPad(Form("%sPad2",cantitle.Data()),Form("%sPad2",cantitle.Data()),0.005,0.005,0.495,0.495,-1,0,0);
    pad2->Draw();
    pad2->SetTopMargin(0.0);
    pad2->SetBottomMargin(0.2);
    pad2->SetLeftMargin(0.22);
    pad2->SetRightMargin(0.02);
    pad2->SetGrid(1,1);
    TPad * pad3 = new TPad(Form("%sPad3",cantitle.Data()),Form("%sPad3",cantitle.Data()),0.5,0.5,0.995,0.995,-1,0,0);
    pad3->Draw();
    pad3->SetBottomMargin(0.027);
    pad3->SetGrid(1,1);
    pad3->SetLeftMargin(0.21);
    pad3->SetRightMargin(0.03);
    //c->cd(); 
    TPad * pad4 = new TPad(Form("%sPad4",cantitle.Data()),Form("%sPad4",cantitle.Data()),0.5,0.005,0.995,0.495,-1,0,0);
    pad4->Draw();
    pad4->SetTopMargin(0.0);
    pad4->SetBottomMargin(0.2);
    pad4->SetLeftMargin(0.21);
    pad4->SetRightMargin(0.03);
    pad4->SetGrid(1,1);
  } else if (nCompare == 3) {
    stitle2 = _hrefB->GetTitle();
    TPad * pad1 = new TPad(Form("%sPad1",cantitle.Data()),Form("%sPad1",cantitle.Data()),0.005,0.5,0.330,0.995,-1,0,0);
    pad1->Draw();
    pad1->SetLeftMargin(0.22);
    pad1->SetRightMargin(0.02);
    pad1->SetBottomMargin(0.027);
    pad1->SetGrid(1,1);
    //c->cd(); 
    TPad * pad2 = new TPad(Form("%sPad2",cantitle.Data()),Form("%sPad2",cantitle.Data()),0.005,0.005,0.330,0.495,-1,0,0);
    pad2->Draw();
    pad2->SetTopMargin(0.0);
    pad2->SetBottomMargin(0.2);
    pad2->SetLeftMargin(0.22);
    pad2->SetRightMargin(0.02);
    pad2->SetGrid(1,1);
    TPad * pad3 = new TPad(Form("%sPad3",cantitle.Data()),Form("%sPad3",cantitle.Data()),0.333,0.5,0.663,0.995,-1,0,0);
    pad3->Draw();
    pad3->SetBottomMargin(0.027);
    pad3->SetGrid(1,1);
    pad3->SetLeftMargin(0.21);
    pad3->SetRightMargin(0.03);
    //c->cd(); 
    TPad * pad4 = new TPad(Form("%sPad4",cantitle.Data()),Form("%sPad4",cantitle.Data()),0.333,0.005,0.663,0.495,-1,0,0);
    pad4->Draw();
    pad4->SetTopMargin(0.0);
    pad4->SetBottomMargin(0.2);
    pad4->SetLeftMargin(0.21);
    pad4->SetRightMargin(0.03);
    pad4->SetGrid(1,1);
    TPad * pad5 = new TPad(Form("%sPad5",cantitle.Data()),Form("%sPad5",cantitle.Data()),0.666,0.5,0.995,0.995,-1,0,0);
    pad5->Draw();
    pad5->SetBottomMargin(0.027);
    pad5->SetGrid(1,1);
    pad5->SetLeftMargin(0.21);
    pad5->SetRightMargin(0.03);
    //c->cd(); 
    TPad * pad6 = new TPad(Form("%sPad6",cantitle.Data()),Form("%sPad6",cantitle.Data()),0.666,0.005,0.995,0.495,-1,0,0);
    pad6->Draw();
    pad6->SetTopMargin(0.0);
    pad6->SetBottomMargin(0.2);
    pad6->SetLeftMargin(0.21);
    pad6->SetRightMargin(0.03);
    pad6->SetGrid(1,1);
  } else {
    cout<<"nCompare must be 1,2 or 3.  Entered as: "<<nCompare<<endl;
  };
  //PadA->Draw();
  pad1->cd();
  TH1D * h1 = (TH1D *) _hrefA->Clone(Form("%sH1",cantitle.Data()));
  h1->SetTitle("");
  h1->SetYTitle(ylabel.Data());
  h1->GetYaxis()->SetTitleSize(TitleSize);
  if(nCompare == 1 ) h1->GetYaxis()->SetTitleOffset(YTitleOffset_2Panel);
  if(nCompare == 2 ) h1->GetYaxis()->SetTitleOffset(YTitleOffset_4Panel);
  if(nCompare == 3 ) h1->GetYaxis()->SetTitleOffset(YTitleOffset_6Panel);
  h1->SetStats(kFALSE);
  h1->GetXaxis()->SetLabelSize(0.0);
  h1->GetYaxis()->SetLabelSize(LabelSize);
  h1->SetLabelFont(9);
  h1->Draw();
  TPaveText * lab1 = new TPaveText(0.25,0.78,0.45,0.85,"NDC");
  lab1->AddText(label1.Data());
  lab1->SetTextColor(kBlack);
  lab1->Draw();
  TGraphErrors * g1local = (TGraphErrors *) _g1->Clone(Form("%sG1local",cantitle.Data()));
  g1local->SetMarkerStyle(22);
  g1local->SetMarkerColor(kBlue);
  g1local->SetMarkerSize(1.5);
  g1local->Draw("p");
  TGraphErrors * g2local = (TGraphErrors *) _g2->Clone(Form("%sG2local",cantitle.Data()));
  g2local->SetMarkerStyle(23);
  g2local->SetMarkerColor(kMagenta);
  g2local->SetMarkerSize(1.5);
  g2local->Draw("p");
  TLegend * leg1 = new TLegend(_xminleg,_yminleg,_xmaxleg,_ymaxleg);
  leg1->AddEntry(g1local,g1local->GetTitle(),"lp");
  leg1->AddEntry(g2local,g2local->GetTitle(),"lp");
  leg1->Draw();
  pad2->cd();
  TH1D * h2 = (TH1D *) _hrefA->Clone(Form("%sS2",cantitle.Data()));
  h2->SetTitle("");
  h2->GetXaxis()->SetLabelSize(LabelSize);
  h2->GetYaxis()->SetLabelSize(LabelSize);
  h2->SetStats(kFALSE);
  h2->SetMinimum(0.79);
  h2->SetMaximum(1.21);
  if(cantitle.Contains("AMPT") || cantitle.Contains("Hydjet")) {
    h2->SetMinimum(0.0);
    h2->SetMaximum(2.1);
  }
  h2->GetYaxis()->SetNdivisions(6+100*10+10000*0,kTRUE);
  h2->SetXTitle(h1->GetXaxis()->GetTitle());
  h2->GetXaxis()->SetTitleSize(TitleSize);
  h2->GetXaxis()->SetTitleOffset(0.85);
  h2->SetYTitle(rtitle1.Data());
  h2->GetYaxis()->SetTitleSize(TitleSize);
  if(nCompare == 1 ) h2->GetYaxis()->SetTitleOffset(YTitleOffset_2Panel);
  if(nCompare == 2 ) h2->GetYaxis()->SetTitleOffset(YTitleOffset_4Panel);
  if(nCompare == 3 ) h2->GetYaxis()->SetTitleOffset(YTitleOffset_6Panel);
  h2->Draw();
  Double_t *X1 = g1local->GetX();
  Double_t *Y1 = g1local->GetY();
  Double_t *Y2 = g2local->GetY();
  Double_t *EY1 = g1local->GetEY();
  Double_t *EY2 = g2local->GetEY();
  Double_t rX[100];
  Double_t rY[100];
  Double_t rEY[100];
  Double_t avr = 0;
  Double_t eavr = 0;
  for(Int_t i = 0; i<g1local->GetN(); i++) {
    rX[i]=X1[i];
    Double_t err = 0;
    if(Y2[i]!=0 && Y1[i]!=0) {
      err = sqrt(pow(EY1[i]/Y1[i],2) + pow(EY2[i]/Y2[i],2));
      rY[i] = Y1[i]/Y2[i];
      rEY[i] = err*rY[i];
      if(rEY[i]>0) {
	avr+=rY[i]/pow(rEY[i],2);
	eavr+=1/pow(rEY[i],2);
      }
    } else {
      rY[i]=0;
      rEY[i]=0;
    };
  }
  if(eavr>0) avr/=eavr;
  TArrow * ar1 = new TArrow(-1.2,avr,-0.3,avr,0.01);
  ar1->Draw();
  TGraphErrors * ratio = new TGraphErrors(g1local->GetN(),rX,rY,0,rEY);
  ratio->SetMarkerStyle(20);
  ratio->SetMarkerColor(kBlack);
  ratio->SetMarkerSize(1.5);
  ratio->Draw("p");
  TLine * line1 = new TLine(0.,1.,12.,1.);
  line1->SetLineColor(kRed);
  line1->SetLineStyle(2);
  line1->SetLineWidth(2);
  line1->Draw();
  if(nCompare == 2 || nCompare == 3) {
    rtitle2 = Form("#frac{%s}{%s}",_g3->GetTitle(),_g4->GetTitle());
    pad3->cd();
    TH1D * h3 = _hrefB->Clone(Form("%sH3",cantitle.Data()));
    h3->SetTitle("");
    h3->SetYTitle(ylabel.Data());
    h3->GetYaxis()->SetTitleSize(TitleSize);
    h3->SetStats(kFALSE);
    h3->GetXaxis()->SetLabelSize(0.0);
    h3->GetYaxis()->SetLabelSize(LabelSize);
    if(nCompare == 2)  h3->GetYaxis()->SetTitleOffset(YTitleOffset_4Panel);
    if(nCompare == 3)  h3->GetYaxis()->SetTitleOffset(YTitleOffset_6Panel);
    h3->SetLabelFont(9);
    h3->Draw();
    TGraphErrors * g3local = (TGraphErrors *) _g3->Clone(Form("%sG3local",cantitle.Data()));
    g3local->SetMarkerStyle(22);
    g3local->SetMarkerColor(kBlue);
    g3local->SetMarkerSize(1.5);
    g3local->Draw("p");
    TGraphErrors * g4local = (TGraphErrors *) _g4->Clone(Form("%sG4local",cantitle.Data()));
    g4local->SetMarkerStyle(23);
    g4local->SetMarkerColor(kMagenta);
    g4local->SetMarkerSize(1.5);
    g4local->Draw("p");
    //TLegend * leg2 = new TLegend(_xminleg,_yminleg,_xmaxleg,_ymaxleg);
    //leg2->AddEntry(g3local,g3local->GetTitle(),"lp");
    //leg2->AddEntry(g4local,g4local->GetTitle(),"lp");
    //leg2->Draw();
    TPaveText * lab2 = new TPaveText(0.25,0.78,0.45,0.85,"NDC");
    lab2->AddText(label2.Data());
    lab2->SetTextColor(kBlack);
    lab2->Draw();
    pad4->cd();
    TH1D * h4 = _hrefB->Clone(Form("%sH4",cantitle.Data()));
    h4->SetTitle("");
    h4->SetYTitle(rtitle2.Data());
    h4->GetYaxis()->SetTitleSize(TitleSize);
    h4->GetXaxis()->SetLabelSize(LabelSize);
    h4->GetYaxis()->SetLabelSize(LabelSize);
    h4->SetStats(kFALSE);
    h4->SetMinimum(0.79);
    h4->SetMaximum(1.21);
    if(cantitle.Contains("AMPT") || cantitle.Contains("Hydjet")) {
      h4->SetMinimum(0.);
      h4->SetMaximum(2.1);
    }
    h4->GetYaxis()->SetNdivisions(6+100*10+10000*0,kTRUE);
    h4->SetXTitle("p_{T} (GeV/c)");
    h4->GetXaxis()->SetTitleSize(TitleSize);
    h4->GetXaxis()->SetTitleOffset(0.85);
    h4->GetYaxis()->SetTitleSize(TitleSize);
    if(nCompare==2) h4->GetYaxis()->SetTitleOffset(YTitleOffset_4Panel);
    if(nCompare==3) h4->GetYaxis()->SetTitleOffset(YTitleOffset_6Panel);
    h4->Draw();
    TLine * line2 = new TLine(0.,1.,12.,1.);
    line2->SetLineColor(kRed);
    line2->SetLineStyle(2);
    line2->SetLineWidth(2);
    line2->Draw();
    Double_t *X3 = g3local->GetX();
    Double_t *Y3 = g3local->GetY();
    Double_t *Y4 = g4local->GetY();
    Double_t *EY3 = g3local->GetEY();
    Double_t *EY4 = g4local->GetEY();
    Double_t rX2[100];
    Double_t rY2[100];
    Double_t rEY2[100];
    Double_t avr = 0;
    Double_t eavr = 0;
    for(Int_t i = 0; i<g3local->GetN(); i++) {
      rX2[i]=X3[i];
      Double_t err = 0;
      if(Y3[i]!=0 && Y4[i]!=0) {
	err = sqrt(pow(EY3[i]/Y3[i],2) + pow(EY4[i]/Y4[i],2));
	rY2[i] = Y3[i]/Y4[i];
	rEY2[i] = err*rY2[i];
	avr+=rY2[i]/pow(rEY2[i],2);
	eavr+=1/pow(rEY2[i],2);;
      } else {
	rY2[i]=0;
	rEY2[i]=0;
      };
    }
    if(eavr>0) avr/=eavr;
    TArrow * ar2 = new TArrow(-1.2,avr,-0.3,avr,0.01);
    ar2->Draw();
    TGraphErrors * ratio2 = new TGraphErrors(g3local->GetN(),rX2,rY2,0,rEY2);
    ratio2->SetMarkerStyle(20);
    ratio2->SetMarkerColor(kBlack);
    ratio2->SetMarkerSize(1.5);
    ratio2->Draw("p");
    if(nCompare == 3) {
      rtitle3 = Form("#frac{%s}{%s}",_g5->GetTitle(),_g6->GetTitle());
      pad5->cd();
      TH1D * h5 = _hrefB->Clone(Form("%sH5",cantitle.Data()));
      h5->SetTitle("");
      h5->SetYTitle(ylabel.Data());
      h5->GetYaxis()->SetTitleSize(TitleSize);
      h5->SetStats(kFALSE);
      h5->GetXaxis()->SetLabelSize(0.0);
      h5->GetYaxis()->SetLabelSize(LabelSize);
      h5->GetYaxis()->SetTitleOffset(YTitleOffset_6Panel);
      h5->SetLabelFont(9);
      h5->Draw();
      TGraphErrors * g5local = (TGraphErrors *) _g5->Clone(Form("%sG5local",cantitle.Data()));
      g5local->SetMarkerStyle(22);
      g5local->SetMarkerColor(kBlue);
      g5local->SetMarkerSize(1.5);
      g5local->Draw("p");
      TGraphErrors * g6local = (TGraphErrors *) _g6->Clone(Form("%sG6local",cantitle.Data()));
      g6local->SetMarkerStyle(23);
      g6local->SetMarkerColor(kMagenta);
      g6local->SetMarkerSize(1.5);
      g6local->Draw("p");
      //TLegend * leg3 = new TLegend(_xminleg,_yminleg,_xmaxleg,_ymaxleg);
      //leg3->AddEntry(g5local,g5local->GetTitle(),"lp");
      //leg3->AddEntry(g6local,g6local->GetTitle(),"lp");
      //leg3->Draw();
      TPaveText * lab3 = new TPaveText(0.25,0.78,0.45,0.85,"NDC");
      lab3->AddText(label3.Data());
      lab3->SetTextColor(kBlack);
      lab3->Draw();
      pad6->cd();
      TH1D * h6 = _hrefB->Clone(Form("%sH6",cantitle.Data()));
      h6->SetTitle("");
      h6->SetYTitle(rtitle3.Data());
      h6->GetYaxis()->SetTitleSize(TitleSize);
      h6->GetXaxis()->SetLabelSize(LabelSize);
      h6->GetYaxis()->SetLabelSize(LabelSize);
      h6->SetStats(kFALSE);
      h6->SetMinimum(0.79);
      h6->SetMaximum(1.21);
      if(cantitle.Contains("AMPT") || cantitle.Contains("Hydjet")) {
	h6->SetMinimum(0.);
	h6->SetMaximum(2.1);
      }

      h6->GetYaxis()->SetNdivisions(6+100*10+10000*0,kTRUE);
      h6->SetXTitle("p_{T} (GeV/c)");
      h6->GetXaxis()->SetTitleSize(TitleSize);
      h6->GetXaxis()->SetTitleOffset(0.85);
      h6->GetYaxis()->SetTitleSize(TitleSize);
      h6->GetYaxis()->SetTitleOffset(YTitleOffset_6Panel);
      h6->Draw();
      TLine * line3 = new TLine(0.,1.,12.,1.);
      line3->SetLineColor(kRed);
      line3->SetLineStyle(2);
      line3->SetLineWidth(2);
      line3->Draw();
      Double_t *X5 = g5local->GetX();
      Double_t *Y5 = g5local->GetY();
      Double_t *Y6 = g6local->GetY();
      Double_t *EY5 = g5local->GetEY();
      Double_t *EY6 = g6local->GetEY();
      Double_t rX3[100];
      Double_t rY3[100];
      Double_t rEY3[100];
      Double_t avr = 0;
      Double_t eavr = 0;
      for(Int_t i = 0; i<g5local->GetN(); i++) {
	rX3[i]=X5[i];
	Double_t err = 0;
	if(Y5[i]!=0 && Y6[i]!=0) {
	  err = sqrt(pow(EY5[i]/Y5[i],2) + pow(EY6[i]/Y6[i],2));
	  rY3[i] = Y5[i]/Y6[i];
	  rEY3[i] = err*rY3[i];
	  avr+=rY3[i]/pow(rEY3[i],2);
	  eavr+=1/pow(rEY3[i],2);;
	} else {
	  rY3[i]=0;
	  rEY3[i]=0;
	};
      }
    if(eavr>0) avr/=eavr;
    TArrow * ar3 = new TArrow(-1.2,avr,-0.3,avr,0.01);
    ar3->Draw();
      TGraphErrors * ratio3 = new TGraphErrors(g5local->GetN(),rX3,rY3,0,rEY3);
      ratio3->SetMarkerStyle(20);
      ratio3->SetMarkerColor(kBlack);
      ratio3->SetMarkerSize(1.5);
      ratio3->Draw("p");
    }
  }
  PadC->cd();
  PadC->SetTopMargin(0.1);
  PadC->SetBottomMargin(0.15);
  gPad->SetGrid(1,1);
  TLegend * pavleg = new TLegend(0.2,0.18,0.65,0.35);
  if(nEP1>=0) {
    TH1D * resc1 = (TH1D *) Rescor1->Get(Form("rescor_%s",EPNames[nEP1].data()));
    resc1->SetTitle("");
    resc1->SetStats(kFALSE);
    resc1->SetXTitle("Centrality");
    resc1->SetYTitle("ResCor");
    resc1->SetMinimum(0.0);
    resc1->SetMaximum(1.);
    resc1->SetMarkerStyle(21);
    resc1->SetMarkerColor(kRed);
    resc1->SetLineColor(kRed);
    resc1->GetYaxis()->SetTitleOffset(1.2);
    resc1->Draw();
    pavleg->AddEntry(resc1,EPNames[nEP1].data(),"p");
  }
  if(nEP2>=0) {
    TH1D * resc2 = (TH1D *) Rescor1->Get(Form("rescor_%s",EPNames[nEP2].data()));
    resc2->SetTitle("");
    resc2->SetStats(kFALSE);
    resc2->SetXTitle("Centrality");
    resc2->SetYTitle("ResCor");
    resc2->SetMinimum(0.0);
    resc2->SetMaximum(1.);
    resc2->SetLineColor(kGreen+1);
    resc2->SetMarkerStyle(24);
    resc2->SetMarkerColor(kGreen+1);
    resc2->GetYaxis()->SetTitleOffset(1.2);
    pavleg->AddEntry(resc2,EPNames[nEP2].data(),"p");
    if(nEP1<0) {
      resc2->Draw();
    } else {
      resc2->Draw("same");
    }
  }
  TPaveText * pavres = new TPaveText(0.5,0.8,0.85,0.87,"NDC");
  pavres->AddText(_g1->GetTitle());
  pavres->Draw();
  pavleg->Draw();
  PadB->cd();
  PadB->SetTopMargin(0.02);
  PadB->SetBottomMargin(0.25);
  TLegend * pavleg2 = new TLegend(0.2,0.29,0.65,0.46);
  gPad->SetGrid(1,1);
  if(nEP3>=0) {
    TH1D * resc3 = (TH1D *) Rescor2->Get(Form("rescor_%s",EPNames[nEP3].data()));
    resc3->SetTitle("");
    resc3->SetStats(kFALSE);
    resc3->SetXTitle("Centrality");
    resc3->SetYTitle("ResCor");
    resc3->SetMarkerStyle(21);
    resc3->SetMarkerColor(kRed);
    resc3->SetLineColor(kRed);
    resc3->GetYaxis()->SetTitleOffset(1.2);
    resc3->SetMinimum(0.0);
    resc3->SetMaximum(1.0);
    resc3->Draw();
    pavleg2->AddEntry(resc3,EPNames[nEP3].data(),"p");
  }
  if(nEP4>=0) {
    TH1D * resc4 = (TH1D *) Rescor2->Get(Form("rescor_%s",EPNames[nEP4].data()));
    resc4->SetTitle("");
    resc4->SetStats(kFALSE);
    resc4->SetXTitle("Centrality");
    resc4->SetYTitle("ResCor");
    resc4->SetLineColor(kGreen+1);
    resc4->SetMarkerStyle(24);
    resc4->SetMarkerColor(kGreen+1);
    resc4->GetYaxis()->SetTitleOffset(1.2);
    resc4->SetMinimum(0.0);
    resc4->SetMaximum(1.0);
    pavleg2->AddEntry(resc4,EPNames[nEP4].data(),"p");
    if(nEP3<0) {
      resc4->Draw();
    } else {
      resc4->Draw("same");
    }
  }
  TPaveText * pavres2 = new TPaveText(0.5,0.89,0.85,0.96,"NDC");
  pavres2->AddText(_g2->GetTitle());
  if(nEP3>=0 || nEP4>=0) {
    pavres2->Draw();
    pavleg2->Draw();
  }

  return c;
}
